<?php
$chBio = [
    "Faruzan"=>["element"=>"Anemo", "weapon"=>"Bow", "star"=>4, "region"=>"Sumeru", "fullName"=>"Madam Faruzan", "alias"=>"Enigmatic Machinist"],
    "Wanderer"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>5, "region"=>"Sumeru", "fullName"=>"Scaramouche (Wanderer)", "alias"=>"Eons Adrift"],
    "Albedo"=>["element"=>"Geo", "weapon"=>"Sword", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Amber"=>["element"=>"Pyro", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"The Outrider", "alias"=>"Gliding Champion"],
    "Ayaka"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Kamisato Ayaka", "alias"=>"Frostflake Heron"],
    "Ayato"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Kamisato Ayato", "alias"=>"Pillar of Fortitude"],
    "Barbara"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Barbara Pegg", "alias"=>"Shining Idol"],
    "Beidou"=>["element"=>"Electro", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Captain of the Crux", "alias"=>"Uncrowned Lord of the Ocean"],
    "Bennett"=>["element"=>"Pyro", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Benny", "alias"=>"Trial by Fire"],
    "Candace"=>["element"=>"Hydro", "weapon"=>"Polearm", "star"=>4, "region"=>"Sumeru", "fullName"=>"Guardian of Aaru Village", "alias"=>"Golden Vow"],
    "Childe"=>["element"=>"Hydro", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Ajax", "alias"=>"Tartaglia"],
    "Chongyun"=>["element"=>"Cryo", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Popsicle Boy", "alias"=>"Frozen Ardor"],
    "Collei"=>["element"=>"Dendro", "weapon"=>"Bow", "star"=>4, "region"=>"Sumeru", "fullName"=>"Trainee Forest Ranger", "alias"=>"Sprout of Rebirth"],
    "Cyno"=>["element"=>"Electro", "weapon"=>"Polearm", "star"=>5, "region"=>"Sumeru", "fullName"=>"General Mahamatra", "alias"=>"Judicator of Secrets"],
    "Diluc"=>["element"=>"Pyro", "weapon"=>"Claymore", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Diluc Ragnvindr", "alias"=>"The Dark Side of Dawn"],
    "Diona"=>["element"=>"Cryo", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Diona Kätzlein", "alias"=>"Kätzlein Cocktail"],
    "Dori"=>["element"=>"Electro", "weapon"=>"Claymore", "star"=>4, "region"=>"Sumeru", "fullName"=>"Dori Sangemah Bay", "alias"=>"Treasure of Dream Garden"],
    "Eula"=>["element"=>"Cryo", "weapon"=>"Claymore", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Eula Lawrence", "alias"=>"Dance of the Shimmering Wave"],
    "Fischl"=>["element"=>"Electro", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Amy", "alias"=>"Prinzessin der Verurteilung!"],
    "Ganyu"=>["element"=>"Cryo", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Coco Goat", "alias"=>"Plenilune Gaze"],
    "Gorou"=>["element"=>"Geo", "weapon"=>"Bow", "star"=>4, "region"=>"Inazuma", "fullName"=>"Miss Hina", "alias"=>"Canine Warrior"],
    "Heizou"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Inazuma", "fullName"=>"Shikanoin Heizou", "alias"=>"Analytical Harmony"],
    "Hu_Tao"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Director of the Wangsheng Funeral Parlor ", "alias"=>"Fragrance in Thaw"],
    "Itto"=>["element"=>"Geo", "weapon"=>"Claymore", "star"=>5, "region"=>"Inazuma", "fullName"=>"Arataki Itto", "alias"=>"Hanamizaka Heroics"],
    "Jean"=>["element"=>"Anemo", "weapon"=>"Sword", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Jean Gunnhildr", "alias"=>"Dandelion Knight"],
    "Kaeya"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Kaeya Alberich", "alias"=>"Frostwind Swordsman"],
    "Kazuha"=>["element"=>"Anemo", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Kaedehara Kazuha", "alias"=>"Scarlet Leaves Pursue Wild Waves"],
    "Keqing"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>5, "region"=>"Liyue", "fullName"=>"Yuheng of the Liyue Qixing", "alias"=>"Driving Thunder"],
    "Klee"=>["element"=>"Pyro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Spark Knight", "alias"=>"Fleeing Sunlight"],
    "Kokomi"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Inazuma", "fullName"=>"Sangonomiya Kokomi", "alias"=>"Pearl of Wisdom"],
    "Kuki_Shinobu"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>4, "region"=>"Inazuma", "fullName"=>"Deputy Leader of Arataki Gang", "alias"=>"Mender of Tribulations"],
    "Layla"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>4, "region"=>"Sumeru", "fullName"=>"Chronically Sleep-deprived", "alias"=>"Fantastical Evening Star"],
    "Lisa"=>["element"=>"Electro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Lisa Minci", "alias"=>"Witch of Purple Rose"],
    "Mona"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Astrologist Mona Megistus", "alias"=>"Astral Reflection"],
    "Nahida"=>["element"=>"Dendro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Sumeru", "fullName"=>"Lesser Lord Kusanali", "alias"=>"Physic of Purity"],
    "Nilou"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>5, "region"=>"Sumeru", "fullName"=>"Dancer under the Zubayr Theater", "alias"=>"Dance of Lotuslight"],
    "Ningguang"=>["element"=>"Geo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Liyue", "fullName"=>"The Tianquan of the Liyue Qixing", "alias"=>"Eclipsing Star"],
    "Noelle"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Maid of the Knights of Favonius", "alias"=>"Chivalric Blossom"],
    "Qiqi"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>5, "region"=>"Liyue", "fullName"=>"Zombie Girl", "alias"=>"Icy Resurrection"],
    "Raiden"=>["element"=>"Electro", "weapon"=>"Polearm", "star"=>5, "region"=>"Inazuma", "fullName"=>"Raiden Ei", "alias"=>"Plane of Euthymia"],
    "Razor"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Razor", "alias"=>"Wolf Boy"],
    "Rosaria"=>["element"=>"Cryo", "weapon"=>"Polearm", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Too Hot to be a Nun", "alias"=>"Thorny Benevolence"],
    "Sara"=>["element"=>"Electro", "weapon"=>"Bow", "star"=>4, "region"=>"Inazuma", "fullName"=>"Kujou Sara", "alias"=>"Crowfeather Kaburaya"],
    "Sayu"=>["element"=>"Anemo", "weapon"=>"Polearm", "star"=>4, "region"=>"Inazuma", "fullName"=>"Sleepy Ninja", "alias"=>"Mujina Ninja"],
    "Shenhe"=>["element"=>"Cryo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Disciple of Cloud Retainer", "alias"=>"Lonesome Transcendence"],
    "Sucrose"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"C<sub>12</sub>H<sub>22</sub>O<sub>11</sub>", "alias"=>"Harmless Sweetie"],
    "Thoma"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>4, "region"=>"Inazuma", "fullName"=>"Malewifou", "alias"=>"Protector From Afar"],
    "Tighnari"=>["element"=>"Dendro", "weapon"=>"Bow", "star"=>5, "region"=>"Sumeru", "fullName"=>"Forest Watcher", "alias"=>"Verdant Strider"],
    "Venti"=>["element"=>"Anemo", "weapon"=>"Bow", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Barbatos", "alias"=>"Windborne Bard"],
    "Xiangling"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>4, "region"=>"Liyue", "fullName"=>"Head Chef at the Wanmin Restaurant", "alias"=>"Exquisite Delicacy"],
    "Xiao"=>["element"=>"Anemo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Yaksha Alatus", "alias"=>"Vigilant Yaksha"],
    "Xingqiu"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>4, "region"=>"Liyue", "fullName"=>"Practitioner of the Guhua Clan's Arts", "alias"=>"Juvenile Galant"],
    "Xinyan"=>["element"=>"Pyro", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Rocn'n'Roll Performer", "alias"=>"Blazing Riff"],
    "Yae_Miko"=>["element"=>"Electro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Inazuma", "fullName"=>"Guuji Yae", "alias"=>"Astute Amusement"],
    "Yanfei"=>["element"=>"Pyro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Liyue", "fullName"=>"Premier Legal Adviser", "alias"=>"Wise Innocence"],
    "Yelan"=>["element"=>"Hydro", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Ningguang's Intelligence Agent ", "alias"=>"Valley Orchid"],
    "Yoimiya"=>["element"=>"Pyro", "weapon"=>"Bow", "star"=>5, "region"=>"Inazuma", "fullName"=>"Naganohara Yoimiya", "alias"=>"Frolicking Flames"],
    "Yun_Jin"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>4, "region"=>"Liyue", "fullName"=>"Director of Yun-Han Opera Troupe", "alias"=>"Stage Lucida"],
    "Zhongli"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Rex Lapis", "alias"=>"Vago Mundo"],
    
];

$chBio2 = [ "Faruzan"=>["bd"=>"August 20th", "mbti"=>"ESTJ", "zodiac"=>"Leo"],
"Wanderer"=>["bd"=>"January 3rd", "mbti"=>"INTJ", "zodiac"=>"Capricorn"],
"Albedo"=>["bd"=>"September 13th", "mbti"=>"INTP", "zodiac"=>"Virgo"],
"Amber"=>["bd"=>"August 10th", "mbti"=>"ESFJ", "zodiac"=>"Leo"],
"Ayaka"=>["bd"=>"September 28th", "mbti"=>"INFJ", "zodiac"=>"Libra"],
"Ayato"=>["bd"=>"March 26th", "mbti"=>"ENTJ", "zodiac"=>"Aries"],
"Barbara"=>["bd"=>"July 5th", "mbti"=>"ESFJ", "zodiac"=>"Cancer"],
"Beidou"=>["bd"=>"February 14th", "mbti"=>"ESTP", "zodiac"=>"Aquarius"],
"Bennett"=>["bd"=>"February 29th", "mbti"=>"ESFP", "zodiac"=>"Pisces"],
"Candace"=>["bd"=>"May 3rd", "mbti"=>"ESFJ", "zodiac"=>"Taurus"],
"Childe"=>["bd"=>"July 20th", "mbti"=>"ESTP", "zodiac"=>"Cancer"],
"Chongyun"=>["bd"=>"September 7th", "mbti"=>"ISFJ", "zodiac"=>"Virgo"],
"Collei"=>["bd"=>"May 8th", "mbti"=>"INFP", "zodiac"=>"Taurus"],
"Cyno"=>["bd"=>"June 23rd", "mbti"=>"ISTP", "zodiac"=>"Cancer"],
"Diluc"=>["bd"=>"April 30th", "mbti"=>"INTJ", "zodiac"=>"Taurus"],
"Diona"=>["bd"=>"January 18th", "mbti"=>"ISFP", "zodiac"=>"Capricorn"],
"Dori"=>["bd"=>"December 21st", "mbti"=>"ESTP", "zodiac"=>"Sagittarius"],
"Eula"=>["bd"=>"October 25th", "mbti"=>"ENTJ", "zodiac"=>"Scorpio"],
"Fischl"=>["bd"=>"May 27th", "mbti"=>"INFP", "zodiac"=>"Gemini"],
"Ganyu"=>["bd"=>"December 2nd", "mbti"=>"ISFJ", "zodiac"=>"Sagittarius"],
"Gorou"=>["bd"=>"May 18th", "mbti"=>"ISFJ", "zodiac"=>"Taurus"],
"Heizou"=>["bd"=>"July 24th", "mbti"=>"ENTP", "zodiac"=>"Leo"],
"Hu_Tao"=>["bd"=>"July 15th", "mbti"=>"ENFP", "zodiac"=>"Caner"],
"Itto"=>["bd"=>"June 1st", "mbti"=>"ESFP", "zodiac"=>"Gemini"],
"Jean"=>["bd"=>"March 14th", "mbti"=>"ISFJ", "zodiac"=>"Pisces"],
"Kaeya"=>["bd"=>"November 30th", "mbti"=>"ENTP", "zodiac"=>"Sagittarius"],
"Kazuha"=>["bd"=>"October 29th", "mbti"=>"ISFP", "zodiac"=>"Scorpio"],
"Keqing"=>["bd"=>"November 20th", "mbti"=>"ENTJ", "zodiac"=>"Scorpio"],
"Klee"=>["bd"=>"July 27th", "mbti"=>"ESFP", "zodiac"=>"Leo"],
"Kokomi"=>["bd"=>"February 22nd", "mbti"=>"INTP", "zodiac"=>"Pisces"],
"Kuki_Shinobu"=>["bd"=>"July 27th", "mbti"=>"ESTJ", "zodiac"=>"Leo"],
"Layla"=>["bd"=>"December 19th", "mbti"=>"INFP", "zodiac"=>"Sagittarius"],
"Lisa"=>["bd"=>"June 9th", "mbti"=>"ENTJ", "zodiac"=>"Gemini"],
"Mona"=>["bd"=>"August 31st", "mbti"=>"INTJ", "zodiac"=>"Virgo"],
"Nahida"=>["bd"=>"October 27th", "mbti"=>"INFJ", "zodiac"=>"Scorpio"],
"Nilou"=>["bd"=>"December 3rd", "mbti"=>"ESFJ", "zodiac"=>"Sagittarius"],
"Ningguang"=>["bd"=>"August 26th", "mbti"=>"ESTJ", "zodiac"=>"Virgo"],
"Noelle"=>["bd"=>"March 21st", "mbti"=>"ESFJ", "zodiac"=>"Aries"],
"Qiqi"=>["bd"=>"March 3rd", "mbti"=>"INFP", "zodiac"=>"Pisces"],
"Raiden"=>["bd"=>"June 26th", "mbti"=>"ISTJ", "zodiac"=>"Cancer"],
"Razor"=>["bd"=>"September 9th", "mbti"=>"ISFP", "zodiac"=>"Virgo"],
"Rosaria"=>["bd"=>"January 24th", "mbti"=>"ISTP", "zodiac"=>"Aquarius"],
"Sara"=>["bd"=>"July 14th", "mbti"=>"ISTJ", "zodiac"=>"Cancer"],
"Sayu"=>["bd"=>"October 19th", "mbti"=>"INFP", "zodiac"=>"Libra"],
"Shenhe"=>["bd"=>"March 10th", "mbti"=>"ISTP", "zodiac"=>"Pisces"],
"Sucrose"=>["bd"=>"November 26th", "mbti"=>"INTP", "zodiac"=>"Sagittarius"],
"Thoma"=>["bd"=>"January 9th", "mbti"=>"ESFJ", "zodiac"=>"Capricorn"],
"Tighnari"=>["bd"=>"December 29th", "mbti"=>"ISTJ", "zodiac"=>"Capricorn"],
"Venti"=>["bd"=>"June 16th", "mbti"=>"ENFP", "zodiac"=>"Gemini"],
"Xiangling"=>["bd"=>"November 2nd", "mbti"=>"ESFP", "zodiac"=>"Scorpio"],
"Xiao"=>["bd"=>"April 17th", "mbti"=>"ISTP", "zodiac"=>"Aries"],
"Xingqiu"=>["bd"=>"October 9th", "mbti"=>"INFJ", "zodiac"=>"Libra"],
"Xinyan"=>["bd"=>"October 16th", "mbti"=>"ESFP", "zodiac"=>"Libra"],
"Yae_Miko"=>["bd"=>"June 27th", "mbti"=>"ENTP", "zodiac"=>"Cancer"],
"Yanfei"=>["bd"=>"July 28th", "mbti"=>"ESTJ", "zodiac"=>"Leo"],
"Yelan"=>["bd"=>"April 20th", "mbti"=>"ENTP", "zodiac"=>"Taurus"],
"Yoimiya"=>["bd"=>"June 21st", "mbti"=>"ENFP", "zodiac"=>"Cancer"],
"Yun_Jin"=>["bd"=>"May 21st", "mbti"=>"ISFP", "zodiac"=>"Taurus"],
"Zhongli"=>["bd"=>"December 31st", "mbti"=>"ISTJ", "zodiac"=>"Capricorn"],
]
?>