<?php
$chBio = [
    "Faruzan"=>["element"=>"Anemo", "weapon"=>"Bow", "star"=>4, "region"=>"Sumeru", "fullName"=>"Madam Faruzan", "alias"=>"Enigmatic Machinist"],
    "Wanderer"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>5, "region"=>"Sumeru", "fullName"=>"Scaramouche (Wanderer)", "alias"=>"Eons Adrift"],
    "Albedo"=>["element"=>"Geo", "weapon"=>"Sword", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Amber"=>["element"=>"Pyro", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"The Outrider", "alias"=>"Gliding Champion"],
    "Ayaka"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Kamisato Ayaka", "alias"=>"Frostflake Heron"],
    "Ayato"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Kamisato Ayato", "alias"=>"Pillar of Fortitude"],
    "Barbara"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Barbara Pegg", "alias"=>"Shining Idol"],
    "Beidou"=>["element"=>"Electro", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Beidou", "alias"=>"Uncrowned Lord of the Ocean"],
    "Bennett"=>["element"=>"Pyro", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Candace"=>["element"=>"Hydro", "weapon"=>"Polearm", "star"=>4, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Childe"=>["element"=>"Hydro", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Chongyun"=>["element"=>"Cryo", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Collei"=>["element"=>"Dendro", "weapon"=>"Bow", "star"=>4, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Cyno"=>["element"=>"Electro", "weapon"=>"Polearm", "star"=>5, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Diluc"=>["element"=>"Pyro", "weapon"=>"Claymore", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Diona"=>["element"=>"Cryo", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Dori"=>["element"=>"Electro", "weapon"=>"Claymore", "star"=>4, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Eula"=>["element"=>"Cryo", "weapon"=>"Claymore", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Fischl"=>["element"=>"Electro", "weapon"=>"Bow", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Ganyu"=>["element"=>"Cryo", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Gorou"=>["element"=>"Geo", "weapon"=>"Bow", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Heizou"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Hu_tao"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Itto"=>["element"=>"Geo", "weapon"=>"Claymore", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Jean"=>["element"=>"Anemo", "weapon"=>"Sword", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Kaeya"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Kazuha"=>["element"=>"Anemo", "weapon"=>"Sword", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Keqing"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Klee"=>["element"=>"Pyro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Kokomi"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Kuki_Shinobu"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Layla"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>4, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Lisa"=>["element"=>"Electro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Mona"=>["element"=>"Hydro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Nahida"=>["element"=>"Dendro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Nilou"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>5, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Ningguang"=>["element"=>"Geo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Noelle"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Qiqi"=>["element"=>"Cryo", "weapon"=>"Sword", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Raiden"=>["element"=>"Electro", "weapon"=>"Polearm", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Razor"=>["element"=>"Electro", "weapon"=>"Sword", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Rosaria"=>["element"=>"Cryo", "weapon"=>"Polearm", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Sara"=>["element"=>"Electro", "weapon"=>"Bow", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Sayu"=>["element"=>"Anemo", "weapon"=>"Polearm", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Shenhe"=>["element"=>"Cryo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Sucrose"=>["element"=>"Anemo", "weapon"=>"Catalyst", "star"=>4, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Thoma"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>4, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Tighnari"=>["element"=>"Dendro", "weapon"=>"Bow", "star"=>5, "region"=>"Sumeru", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Venti"=>["element"=>"Anemo", "weapon"=>"Bow", "star"=>5, "region"=>"Mondstadt", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Xiangling"=>["element"=>"Pyro", "weapon"=>"Polearm", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Xiao"=>["element"=>"Anemo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Xingqiu"=>["element"=>"Hydro", "weapon"=>"Sword", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Xinyan"=>["element"=>"Pyro", "weapon"=>"Claymore", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Yae_Miko"=>["element"=>"Electro", "weapon"=>"Catalyst", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Yanfei"=>["element"=>"Pyro", "weapon"=>"Catalyst", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Yelan"=>["element"=>"Hydro", "weapon"=>"Bow", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Yoimiya"=>["element"=>"Pyro", "weapon"=>"Bow", "star"=>5, "region"=>"Inazuma", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Yun_Jin"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>4, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    "Zhongli"=>["element"=>"Geo", "weapon"=>"Polearm", "star"=>5, "region"=>"Liyue", "fullName"=>"Albedo Chief Alchemist", "alias"=>"Kreideprinz"],
    
] 
?>